# Site settings
title: Chris Adams
email: chris@cadams.com.au
description: "I am a software engineer from Melbourne Australia living in San Francisco and working at <a href='//www.pivotallabs.com'>Pivotal Labs</a>. Here, you can read my thoughts on life in SF, software engineering, and the software industry as a whole."
baseurl: ""
url: "http://www.cadams.com.au"
github: thecadams
twitter: cadamsau

# Build settings
markdown: kramdown
permalink: pretty
