# Site settings
theme: jekyll-theme-chirpy
theme_mode: light

title: Chris Adams
email: chris+site@cadams.com.au
avatar: /images/avatar.jpg
tagline: >-
  <p>Software engineer from Melbourne, Australia.</p>
  <p>Living in Sydney and working at <a href='https://www.canva.com'>Canva</a>.</p>
  <p>I write about life, software engineering, Site Reliability Engineering, and entrepreneurship.</p>

baseurl: ""
url: https://www.cadams.com.au

markdown: kramdown
permalink: pretty

github:
  username: thecadams
twitter:
  username: cadamsau

social:
  name: Chris Adams
  email: chris+site@cadams.com.au
  links:
    - https://github.com/thecadams

toc: true

disqus:
  comments: false # boolean type, the global switch for posts comments.
  shortname: "" # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname

paginate: 10

collections:
  tabs:
    output: true
    sort_by: order
